server.port: 9090

spring.cloud.config.server.git.uri: file:///C:/Repository/microservice-configs

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/hanniere/microservice-configs